/*
@Name: Life
@Author: Charles Vestal
@Firmware: latest
@Level: Advanced
@Tags: sequencer, generative, midi, cellular automata
@Description: A Game of Life sequencer. Four voices walk an evolving 16x16 world and play what they find alive.

Life turns Conway's Game of Life into a sequencer. The 16x16 grid is a living
palette, not a piano roll: columns are steps, rows are scale degrees, and the
automaton rewrites the whole thing underneath you on its own clock.

Four independent voices walk through the world, each at its own rate and in its
own direction. When a voice arrives at a column it looks at whichever cells are
alive there and picks one - topmost, nearest to the last note, random, climbing,
falling - or plays all of them at once as a chord. An empty column is a rest, so
the shape of the automaton becomes the rhythm.

Tap any pad to bring a cell to life. Hold the bottom-right pad for mutes, solos,
clear, respawn and transport. Everything else lives on the settings pages.
*/

/* Generated by build/amalgamate.sh - do not edit. Edit the src/ headers and src/panel.cpp. */

/* ===== src/life.h ===== */
/* plinky-life - the cellular automaton.

   Pure C. No Plinky API. Compiled directly by the desktop test harness.

   A 16x16 toroidal Conway world (B3/S23). Columns are steps, rows are scale
   degrees: row 15 is degree 0, row 0 is degree 15. The world is a *palette*
   that voices read, not a piano roll. */

#define LIFE_W 16
#define LIFE_H 16
#define LIFE_CELLS (LIFE_W * LIFE_H)

/* Row-major, world[y * LIFE_W + x]. 1 = alive. */
typedef struct {
    unsigned char cell[LIFE_CELLS];
} life_world_t;

typedef struct {
    int alive;      /* live cells after the step */
    int births;     /* cells born this generation */
    int deaths;     /* cells that died this generation */
    int unchanged;  /* cells identical to the previous generation */
} life_stats_t;

static inline int life_get(const life_world_t *w, int x, int y) {
    return w->cell[(y & 15) * LIFE_W + (x & 15)] ? 1 : 0;
}

static inline void life_set(life_world_t *w, int x, int y, int alive) {
    w->cell[(y & 15) * LIFE_W + (x & 15)] = alive ? 1 : 0;
}

static inline void life_toggle(life_world_t *w, int x, int y) {
    unsigned char *c = &w->cell[(y & 15) * LIFE_W + (x & 15)];
    *c = *c ? 0 : 1;
}

static inline void life_clear(life_world_t *w) {
    for (int i = 0; i < LIFE_CELLS; ++i) w->cell[i] = 0;
}

static inline int life_population(const life_world_t *w) {
    int n = 0;
    for (int i = 0; i < LIFE_CELLS; ++i) n += w->cell[i] ? 1 : 0;
    return n;
}

/* Live cells in column x, as a bitmask over rows: bit r set means row r alive.
   Bit 0 is row 0 (the top row, the highest pitch). */
static inline unsigned short life_column_mask(const life_world_t *w, int x) {
    unsigned short m = 0;
    x &= 15;
    for (int y = 0; y < LIFE_H; ++y)
        if (w->cell[y * LIFE_W + x]) m |= (unsigned short)(1u << y);
    return m;
}

/* Toroidal neighbour count. Edges wrap, which is what keeps small worlds
   musically alive - a bounded 16x16 clips gliders dead at the border. */
static inline int life_neighbours(const life_world_t *w, int x, int y) {
    int n = 0;
    for (int dy = -1; dy <= 1; ++dy)
        for (int dx = -1; dx <= 1; ++dx) {
            if (dx == 0 && dy == 0) continue;
            n += w->cell[((y + dy) & 15) * LIFE_W + ((x + dx) & 15)] ? 1 : 0;
        }
    return n;
}

/* Advance one generation of B3/S23 into `next`, reporting what changed.
   `next` must not alias `w`. */
static inline void life_step(const life_world_t *w, life_world_t *next, life_stats_t *stats) {
    int alive = 0, births = 0, deaths = 0, unchanged = 0;
    for (int y = 0; y < LIFE_H; ++y) {
        for (int x = 0; x < LIFE_W; ++x) {
            int was = w->cell[y * LIFE_W + x] ? 1 : 0;
            int n = life_neighbours(w, x, y);
            int now = was ? (n == 2 || n == 3) : (n == 3);
            next->cell[y * LIFE_W + x] = (unsigned char)now;
            if (now) ++alive;
            if (now && !was) ++births;
            else if (!now && was) ++deaths;
            else ++unchanged;
        }
    }
    if (stats) {
        stats->alive = alive;
        stats->births = births;
        stats->deaths = deaths;
        stats->unchanged = unchanged;
    }
}

/* --- Liveness -------------------------------------------------------------

   Pure Conway on a 16x16 torus settles into still-lifes and blinkers within
   roughly 100-200 generations. When the palette freezes, four playheads walking
   it become a static loop and the instrument dies. Auto-respawn is therefore
   load-bearing, not a nicety. */

typedef struct {
    int stable_gens;     /* consecutive generations with no births and no deaths */
    unsigned int rng;    /* xorshift32 state; seeded non-zero */
} life_respawn_t;

static inline unsigned int life_rand(unsigned int *state) {
    unsigned int x = *state ? *state : 0x1234567u;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    *state = x;
    return x;
}

static inline void life_respawn_init(life_respawn_t *r, unsigned int seed) {
    r->stable_gens = 0;
    r->rng = seed ? seed : 0x1234567u;
}

/* Feed each generation's stats in. Returns non-zero when the world needs help:
   either population has fallen below `density_floor`, or nothing has changed for
   `stable_limit` generations (a still-life or a period-1 lock).

   Oscillators such as blinkers keep births and deaths non-zero, so they do NOT
   count as stable - which is correct, a blinking world is still making music. */
static inline int life_respawn_tick(life_respawn_t *r, const life_stats_t *stats,
                                    int density_floor, int stable_limit) {
    if (stats->births == 0 && stats->deaths == 0) ++r->stable_gens;
    else r->stable_gens = 0;

    if (stats->alive < density_floor) return 1;
    if (stable_limit > 0 && r->stable_gens >= stable_limit) return 1;
    return 0;
}

/* Sprinkle `count` live cells into random dead positions. Gives up after a
   bounded number of attempts so a nearly-full world cannot spin. */
static inline void life_respawn_apply(life_world_t *w, life_respawn_t *r, int count) {
    int attempts = count * 8 + 16;
    while (count > 0 && attempts-- > 0) {
        int i = (int)(life_rand(&r->rng) % (unsigned int)LIFE_CELLS);
        if (!w->cell[i]) {
            w->cell[i] = 1;
            --count;
        }
    }
    r->stable_gens = 0;
}

/* ===== src/selection.h ===== */
/* plinky-life - selection rules.

   Pure C. No Plinky API. Compiled directly by the desktop test harness.

   Traversal and selection are deliberately separate concepts:

     traversal  = which column a voice is on   -> handled by playhead_t
     selection  = which live cell in that column actually sounds -> this file

   ZOA's feature list conflates the two. Keeping them apart is what makes the
   behaviour describable, and testable without any hardware.

   Rows are scale degrees: row 15 is degree 0 (lowest pitch), row 0 is degree 15
   (highest pitch). Rules are named in terms of PITCH, not row index, because
   that is what a player hears. "Up" means up in pitch, i.e. toward row 0.

   An empty column is a rest. That is load-bearing: it is what makes the
   automaton's density read as rhythm instead of a wall of notes. */

typedef enum {
    SEL_FIRST = 0,  /* topmost live cell (highest pitch) */
    SEL_LAST,       /* bottommost live cell (lowest pitch) */
    SEL_UP,         /* cycle through live cells, ascending in pitch */
    SEL_DOWN,       /* cycle through live cells, descending in pitch */
    SEL_UPDOWN,     /* ping-pong, ascending first, endpoints not repeated */
    SEL_DOWNUP,     /* ping-pong, descending first */
    SEL_RANDOM,     /* uniform pick among live cells */
    SEL_WALK,       /* live cell nearest in pitch to the previous note */
    SEL_RISE,       /* nearest live cell strictly above the previous, wrapping */
    SEL_FALL,       /* nearest live cell strictly below the previous, wrapping */
    SEL_ALL,        /* every live cell at once - the only rule that makes chords */
    SEL_COUNT
} selection_rule_t;

/* 4-char labels for draw_system_style_enum_settings_page(...). */
static const char *const life_sel_names[SEL_COUNT] = {
    "FRST", "LAST", "UP  ", "DOWN", "UPDN", "DNUP", "RAND", "WALK", "RISE", "FALL", "ALL "
};

typedef struct {
    short cycle_idx;    /* position within the pitch-ascending live-cell list */
    short prev_row;     /* row of the previous note, or -1 if none yet */
    signed char dir;    /* ping-pong direction: +1 ascending, -1 descending */
    unsigned int rng;   /* xorshift32 state for SEL_RANDOM */
} selection_state_t;

static inline void selection_reset(selection_state_t *s, unsigned int seed) {
    s->cycle_idx = 0;
    s->prev_row = -1;
    s->dir = 1;
    s->rng = seed ? seed : 0x9e3779b9u;
}

static inline unsigned int selection_rand(selection_state_t *s) {
    unsigned int x = s->rng ? s->rng : 0x9e3779b9u;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    s->rng = x;
    return x;
}

/* Fill `rows` with the live row indices in PITCH-ASCENDING order (row 15 first,
   row 0 last) and return how many there were. */
static inline int selection_collect(unsigned short col_mask, int *rows) {
    int n = 0;
    for (int y = 15; y >= 0; --y)
        if (col_mask & (unsigned short)(1u << y)) rows[n++] = y;
    return n;
}

/* Choose which live cells in this column sound.

   Returns a row bitmask: 0 means rest, one bit for the single-note rules, and
   the whole column for SEL_ALL.

   Every rule that retains state across ticks (UP, DOWN, UPDOWN, DOWNUP, WALK,
   RISE, FALL) must survive the live-cell set changing size underneath it -
   which it constantly will, because the automaton is rewriting the column
   between ticks. The retained index is therefore clamped into range on read and
   never assumed valid from the previous tick. */
static inline unsigned short selection_pick(selection_state_t *s, unsigned short col_mask,
                                            selection_rule_t rule) {
    int rows[16];
    int n = selection_collect(col_mask, rows);

    if (n == 0) return 0;             /* empty column -> rest */
    if (rule == SEL_ALL) {
        s->prev_row = (short)rows[n - 1];
        return col_mask;
    }

    int chosen;                        /* index into `rows`, pitch-ascending */

    switch (rule) {
    case SEL_FIRST:
        chosen = n - 1;                /* highest pitch = topmost row */
        break;

    case SEL_LAST:
        chosen = 0;                    /* lowest pitch = bottommost row */
        break;

    case SEL_UP:
        chosen = (s->cycle_idx + 1) % n;
        break;

    case SEL_DOWN:
        chosen = ((s->cycle_idx - 1) % n + n) % n;
        break;

    case SEL_UPDOWN:
    case SEL_DOWNUP:
        if (n == 1) {
            chosen = 0;
        } else {
            int dir = s->dir >= 0 ? 1 : -1;
            if (rule == SEL_DOWNUP && s->prev_row < 0) dir = -1;
            int idx = s->cycle_idx;
            if (idx >= n) idx = n - 1;
            if (idx < 0) idx = 0;
            idx += dir;
            if (idx >= n) { idx = n - 2; dir = -1; }   /* endpoint not repeated */
            else if (idx < 0) { idx = 1; dir = 1; }
            chosen = idx;
            s->dir = (signed char)dir;
        }
        break;

    case SEL_RANDOM:
        chosen = (int)(selection_rand(s) % (unsigned int)n);
        break;

    case SEL_WALK: {
        if (s->prev_row < 0) { chosen = n - 1; break; }
        int best = 0, best_d = 32;
        for (int i = 0; i < n; ++i) {
            int d = rows[i] - s->prev_row;
            if (d < 0) d = -d;
            /* strict < keeps the tie-break at the first match in
               pitch-ascending order, i.e. the lower pitch */
            if (d < best_d) { best_d = d; best = i; }
        }
        chosen = best;
        break;
    }

    case SEL_RISE: {
        /* strictly above in pitch = a smaller row index; nearest = the largest
           such row. Wraps to the lowest pitch when there is nothing above. */
        if (s->prev_row < 0) { chosen = 0; break; }
        chosen = -1;
        for (int i = 0; i < n; ++i)
            if (rows[i] < s->prev_row) { chosen = i; break; }
        if (chosen < 0) chosen = 0;
        break;
    }

    case SEL_FALL: {
        /* strictly below in pitch = a larger row index; nearest = the smallest
           such row. Wraps to the highest pitch when there is nothing below. */
        if (s->prev_row < 0) { chosen = n - 1; break; }
        chosen = -1;
        for (int i = n - 1; i >= 0; --i)
            if (rows[i] > s->prev_row) { chosen = i; break; }
        if (chosen < 0) chosen = n - 1;
        break;
    }

    default:
        chosen = n - 1;
        break;
    }

    if (chosen < 0) chosen = 0;
    if (chosen >= n) chosen = n - 1;

    s->cycle_idx = (short)chosen;
    s->prev_row = (short)rows[chosen];
    return (unsigned short)(1u << rows[chosen]);
}

/* How far this note moved from the previous one, 0..127. Drives the per-voice
   "randomness" CC. Returns 0 when there was no previous note. */
static inline int selection_deviation(const selection_state_t *s, int prev_row) {
    if (prev_row < 0 || s->prev_row < 0) return 0;
    int d = s->prev_row - prev_row;
    if (d < 0) d = -d;
    return d * 127 / 15;
}

/* ===== src/traversal.h ===== */
/* plinky-life - column traversal.

   Pure C. No Plinky API. Compiled directly by the desktop test harness.

   Traversal is which column a voice is on. Selection (selection.h) is which
   live cell in that column sounds. Polyrhythm comes from voices having
   different RATES, not different loop lengths - all four span all 16 columns.

   The design originally delegated this to Plinky's `playhead_t`. We do it here
   instead: `llm.txt` documents `playhead_t::update()` as taking
   "`clock_divider_t::update() > 0`" but declares it as `update(int num_steps,
   ...)`, and those two contracts disagree. Panel code cannot be compiled
   locally to settle the question, so twenty lines of our own - testable on the
   desktop like everything else here - is the cheaper risk. */

typedef enum {
    TRAV_FORWARD = 0,
    TRAV_REVERSE,
    TRAV_PINGPONG,
    TRAV_RANDOM,
    TRAV_COUNT
} traversal_order_t;

/* 4-char labels for draw_system_style_enum_settings_page(...). */
static const char *const life_trav_names[TRAV_COUNT] = { "FWD ", "REV ", "PING", "RAND" };

typedef struct {
    short pos;
    signed char dir;
    unsigned int rng;
} traversal_state_t;

static inline void traversal_reset(traversal_state_t *t, traversal_order_t order, int n,
                                   unsigned int seed) {
    t->pos = (order == TRAV_REVERSE) ? (short)(n - 1) : 0;
    t->dir = (order == TRAV_REVERSE) ? -1 : 1;
    t->rng = seed ? seed : 0x2545f491u;
}

static inline unsigned int traversal_rand(traversal_state_t *t) {
    unsigned int x = t->rng ? t->rng : 0x2545f491u;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    t->rng = x;
    return x;
}

/* Advance one step and return the new column, always within 0..n-1.

   The position is clamped on entry rather than trusted, so a stale position
   from a changed setting or a loaded save can never index out of range. */
static inline int traversal_advance(traversal_state_t *t, traversal_order_t order, int n) {
    if (n < 1) n = 1;
    int p = t->pos;
    if (p < 0) p = 0;
    if (p >= n) p = n - 1;

    switch (order) {
    case TRAV_REVERSE:
        p = (p - 1 + n) % n;
        break;

    case TRAV_PINGPONG:
        if (n == 1) {
            p = 0;
        } else {
            int dir = t->dir >= 0 ? 1 : -1;
            p += dir;
            if (p >= n) { p = n - 2; dir = -1; }   /* endpoints are not repeated */
            else if (p < 0) { p = 1; dir = 1; }
            t->dir = (signed char)dir;
        }
        break;

    case TRAV_RANDOM:
        p = (int)(traversal_rand(t) % (unsigned int)n);
        break;

    case TRAV_FORWARD:
    default:
        p = (p + 1) % n;
        break;
    }

    t->pos = (short)p;
    return p;
}

static inline int traversal_position(const traversal_state_t *t, int n) {
    if (n < 1) n = 1;
    int p = t->pos;
    if (p < 0) p = 0;
    if (p >= n) p = n - 1;
    return p;
}

/* ===== src/scales.h ===== */
/* plinky-life - scale tables and degree->note mapping.

   Pure C. No Plinky API. Compiled directly by the desktop test harness.

   A scale is a 12-bit root-relative bitmask, matching Plinky's `current_scale`
   global: bit 0 is the root, bit n is n semitones above it. Every scale below
   therefore round-trips through `set_current_key_and_scale(...)`, so choosing a
   scale here drives the whole instrument's harmonic state rather than keeping a
   private one.

   We deliberately do NOT call `shift_note_along_scale(...)`. It is used inside
   the public header bundle but never declared there, so its exact signature is
   unverifiable from the published API. Doing the mapping here costs ~15 lines
   and keeps this file testable on the desktop. */

#define LIFE_NUM_SCALES 29

static const unsigned short life_scale_masks[LIFE_NUM_SCALES] = {
    0xFFF, /* Chromatic          0 1 2 3 4 5 6 7 8 9 10 11 */
    0xAB5, /* Major              0 2 4 5 7 9 11 */
    0x5AD, /* Natural Minor      0 2 3 5 7 8 10 */
    0x6AD, /* Dorian             0 2 3 5 7 9 10 */
    0x5AB, /* Phrygian           0 1 3 5 7 8 10 */
    0xAD5, /* Lydian             0 2 4 6 7 9 11 */
    0x6B5, /* Mixolydian         0 2 4 5 7 9 10 */
    0x56B, /* Locrian            0 1 3 5 6 8 10 */
    0x295, /* Major Pentatonic   0 2 4 7 9 */
    0x4A9, /* Minor Pentatonic   0 3 5 7 10 */
    0x4E9, /* Blues              0 3 5 6 7 10 */
    0x555, /* Whole Tone         0 2 4 6 8 10 */
    0x9AD, /* Harmonic Minor     0 2 3 5 7 8 11 */
    0xAAD, /* Melodic Minor      0 2 3 5 7 9 11 */
    0xB6D, /* Diminished W-H     0 2 3 5 6 8 9 11 */
    0x6DB, /* Diminished H-W     0 1 3 4 6 7 9 10 */
    0x5B3, /* Phrygian Dominant  0 1 4 5 7 8 10 */
    0x9B3, /* Double Harmonic    0 1 4 5 7 8 11 */
    0x9CD, /* Hungarian Minor    0 2 3 6 7 8 11 */
    0x18B, /* Pelog              0 1 3 7 8 */
    0x18D, /* Hirajoshi          0 2 3 7 8 */
    0x6D5, /* Lydian Dominant    0 2 4 6 7 9 10 */
    0x55B, /* Altered            0 1 3 4 6 8 10 */
    0x9AB, /* Neapolitan Minor   0 1 3 5 7 8 11 */
    0xAAB, /* Neapolitan Major   0 1 3 5 7 9 11 */
    0x4A3, /* In Sen             0 1 5 7 10 */
    0x463, /* Iwato              0 1 5 6 10 */
    0x28D, /* Kumoi              0 2 3 7 9 */
    0x4A5, /* Egyptian           0 2 5 7 10 */
};

/* 4-char labels for draw_system_style_enum_settings_page(...). */
static const char *const life_scale_names[LIFE_NUM_SCALES] = {
    "CHRM",
    "MAJ ",
    "MIN ",
    "DOR ",
    "PHRY",
    "LYD ",
    "MIX ",
    "LOC ",
    "MAJ5",
    "MIN5",
    "BLUE",
    "WHOL",
    "HMIN",
    "MMIN",
    "DIM ",
    "DIM2",
    "SPAN",
    "BHAI",
    "HUNG",
    "PELO",
    "HIRA",
    "LYDD",
    "ALTR",
    "NEAM",
    "NEAJ",
    "INSN",
    "IWAT",
    "KUMO",
    "EGYP",
};

static const char *const life_scale_long_names[LIFE_NUM_SCALES] = {
    "Chromatic",
    "Major",
    "Natural Minor",
    "Dorian",
    "Phrygian",
    "Lydian",
    "Mixolydian",
    "Locrian",
    "Major Pentatonic",
    "Minor Pentatonic",
    "Blues",
    "Whole Tone",
    "Harmonic Minor",
    "Melodic Minor",
    "Diminished W-H",
    "Diminished H-W",
    "Phrygian Dominant",
    "Double Harmonic",
    "Hungarian Minor",
    "Pelog",
    "Hirajoshi",
    "Lydian Dominant",
    "Altered",
    "Neapolitan Minor",
    "Neapolitan Major",
    "In Sen",
    "Iwato",
    "Kumoi",
    "Egyptian",
};

static inline int life_popcount12(unsigned short mask) {
    int n = 0;
    for (int i = 0; i < 12; ++i)
        if (mask & (1u << i)) ++n;
    return n;
}

/* Semitone offset of the idx-th set bit, or -1. */
static inline int life_nth_degree_semitone(unsigned short mask, int idx) {
    for (int i = 0; i < 12; ++i) {
        if (mask & (1u << i)) {
            if (idx == 0) return i;
            --idx;
        }
    }
    return -1;
}

/* Map a scale degree to a MIDI note.

   `degree` may be negative or run past the top of the scale; it wraps into
   octaves. Returns a note clamped to 0..127. An empty mask falls back to
   chromatic so a corrupt save can never produce silence or a divide by zero. */
static inline int life_degree_to_note(int degree, int root, unsigned short mask) {
    if (mask == 0) mask = 0xFFF;
    int n = life_popcount12(mask);
    int octave = degree / n;
    int idx = degree % n;
    if (idx < 0) { idx += n; --octave; }  /* C truncates toward zero; we need floor */
    int note = root + octave * 12 + life_nth_degree_semitone(mask, idx);
    return note < 0 ? 0 : (note > 127 ? 127 : note);
}

/* ===== src/voice.h ===== */
/* plinky-life - note lifecycle.

   Pure C. No Plinky API. Compiled directly by the desktop test harness.

   This owns the question of what is currently sounding and when it stops, and
   nothing else. It does not know about the automaton, and it does not know
   whether a note ends up on Plinky's internal synth or on a MIDI cable - the
   panel decides that by consuming the release list this produces.

   Stuck notes are the classic failure mode for a sequencer with a MIDI sink, so
   every path that stops a voice - mute, rate change, transport stop, panel
   unload - goes through voice_release_all(). There is exactly one way for a
   note to end. */

#define LIFE_MAX_HELD 16   /* SEL_ALL can sound a whole 16-row column at once */

typedef struct {
    unsigned char note;
    unsigned char vel;
    unsigned char active;
    int ticks_left;
} held_note_t;

typedef struct {
    held_note_t held[LIFE_MAX_HELD];
} voice_notes_t;

static inline void voice_notes_init(voice_notes_t *v) {
    for (int i = 0; i < LIFE_MAX_HELD; ++i) {
        v->held[i].note = 0;
        v->held[i].vel = 0;
        v->held[i].active = 0;
        v->held[i].ticks_left = 0;
    }
}

static inline int voice_num_held(const voice_notes_t *v) {
    int n = 0;
    for (int i = 0; i < LIFE_MAX_HELD; ++i) n += v->held[i].active ? 1 : 0;
    return n;
}

/* Start a note. Returns the slot, or -1 if all 16 are busy.

   Re-arming a note that is already sounding refreshes its countdown rather than
   allocating a second slot; two note-ons for one pitch would leave the second
   note-off orphaned on the MIDI side. */
static inline int voice_arm(voice_notes_t *v, int note, int vel, int ticks) {
    for (int i = 0; i < LIFE_MAX_HELD; ++i)
        if (v->held[i].active && v->held[i].note == (unsigned char)note) {
            v->held[i].ticks_left = ticks;
            v->held[i].vel = (unsigned char)vel;
            return i;
        }
    for (int i = 0; i < LIFE_MAX_HELD; ++i)
        if (!v->held[i].active) {
            v->held[i].note = (unsigned char)note;
            v->held[i].vel = (unsigned char)vel;
            v->held[i].active = 1;
            v->held[i].ticks_left = ticks;
            return i;
        }
    return -1;
}

/* Advance every countdown by `ticks`. Notes that expire are appended to
   `released` (which must have room for LIFE_MAX_HELD entries) and the count is
   returned. The caller is responsible for actually sending the note-offs. */
static inline int voice_tick(voice_notes_t *v, int ticks, unsigned char *released) {
    int n = 0;
    for (int i = 0; i < LIFE_MAX_HELD; ++i) {
        if (!v->held[i].active) continue;
        v->held[i].ticks_left -= ticks;
        if (v->held[i].ticks_left <= 0) {
            released[n++] = v->held[i].note;
            v->held[i].active = 0;
        }
    }
    return n;
}

/* Release everything immediately. The single exit path for a voice.
   `released` must have room for LIFE_MAX_HELD entries. */
static inline int voice_release_all(voice_notes_t *v, unsigned char *released) {
    int n = 0;
    for (int i = 0; i < LIFE_MAX_HELD; ++i) {
        if (!v->held[i].active) continue;
        released[n++] = v->held[i].note;
        v->held[i].active = 0;
    }
    return n;
}

/* Note length is a percentage (10..100) of the voice's step interval. Always at
   least 1 tick, so a very short step at a low percentage still produces an
   audible note rather than a note-on immediately followed by a note-off. */
static inline int voice_length_ticks(int step_ticks, int length_percent) {
    if (length_percent < 10) length_percent = 10;
    if (length_percent > 100) length_percent = 100;
    int t = step_ticks * length_percent / 100;
    return t < 1 ? 1 : t;
}

/* ===== src/panel.cpp ===== */

/* ---------------------------------------------------------------------------
   This file does NOT compile on its own. It has no #includes (they are banned
   in panel code) and only type-checks once the IDE injects the SDK headers.

   The pure logic lives in the src/ headers and is desktop-tested by harness/tests.c.
   `sh build/amalgamate.sh` splices those headers in ahead of this file to
   produce the single plinky_life.cpp that gets flashed.
   ------------------------------------------------------------------------- */

#define PANEL_PAD_COLOR WHITE

/* --- Palette --------------------------------------------------------------

   SYSTEM_NOTES.md section 4: the dim tiers are far dimmer than they look.
   WHITE is already LED_RGB(15,15,15), so DIMMEST(WHITE) lands at 3 of 31 and
   DIMMESTEST at 1 - effectively invisible, and a real source of "dead LED" bug
   reports. Every colour here is therefore written out explicitly. */

#define LIFE_COL_ALIVE      LED_RGB(11, 11, 11)
#define LIFE_COL_ALIVE_DIM  LED_RGB(3, 3, 3)     /* world under the action layer */
#define LIFE_COL_MODIFIER   LED_RGB(20, 0, 16)
#define LIFE_COL_ACTION     LED_RGB(0, 10, 12)
#define LIFE_COL_DANGER     LED_RGB(24, 2, 0)
#define LIFE_COL_OFF        LED_RGB(2, 2, 2)

static const uint32_t life_voice_dim[4] = {
    LED_RGB(7, 0, 0), LED_RGB(0, 7, 0), LED_RGB(0, 1, 10), LED_RGB(6, 4, 0),
};
static const uint32_t life_voice_bright[4] = {
    LED_RGB(31, 4, 4), LED_RGB(6, 31, 6), LED_RGB(9, 9, 31), LED_RGB(31, 24, 0),
};

/* --- Rates ---------------------------------------------------------------

   clock_divider_t scales the transport's Q16 quarter-note phase by
   numerator/denominator, so the numerator is "steps per quarter note". */

typedef struct {
    short num;
    short den;
} life_rate_t;

static const life_rate_t life_rates[] = {
    { 8, 1 }, { 6, 1 }, { 4, 1 }, { 3, 1 }, { 2, 1 }, { 3, 2 },
    { 1, 1 }, { 1, 2 }, { 1, 4 }, { 1, 8 }, { 1, 16 }, { 1, 32 },
};

/* Kept as its own array, not a field of life_rate_t, so it can be handed
   straight to draw_system_style_enum_settings_page(...) as a const char* const*
   without building a temporary. */
static const char *const life_rate_names[] = {
    "32nd", "16T ", "16th", "8T  ", "8th ", "4T  ",
    "1/4 ", "1/2 ", "1BAR", "2BAR", "4BAR", "8BAR",
};
#define LIFE_NUM_RATES ((int)(sizeof(life_rates) / sizeof(life_rates[0])))

static const char *const life_note_names[12] = {
    "C   ", "C#  ", "D   ", "D#  ", "E   ", "F   ",
    "F#  ", "G   ", "G#  ", "A   ", "A#  ", "B   ",
};

static const char *const life_sink_names[3] = { "SYN ", "MIDI", "BOTH" };
enum { LIFE_SINK_SYNTH = 0, LIFE_SINK_MIDI, LIFE_SINK_BOTH };

static const char *const life_port_names[5] = { "OFF ", "USB1", "TRS1", "P1  ", "ALL " };
static const uint8_t life_port_values[5] = {
    MIDI_PORT_NONE, MIDI_PORT_USB1, MIDI_PORT_TRS1, MIDI_PORT_1,
    (uint8_t)(MIDI_PORT_1 | MIDI_PORT_2),
};

/* Simulation CCs. Fixed numbers, documented in the README so a patch on the
   receiving end can rely on them. */
#define LIFE_CC_DENSITY   20
#define LIFE_CC_BIRTHS    21
#define LIFE_CC_DEATHS    22
#define LIFE_CC_STABILITY 23
#define LIFE_CC_VOICE_RND 24   /* .. 27, one per voice */
#define LIFE_NUM_CCS      8

#define LIFE_NUM_VOICES 4
#define LIFE_MODIFIER_X 15
#define LIFE_MODIFIER_Y 15

/* Default step length, used for the very first note of a voice before two
   divider edges have been seen and the real interval is known. */
#define LIFE_DEFAULT_STEP_US 250000

struct life_panel : panel_t {
    /* --- world --- */
    life_world_t world;
    life_world_t scratch;
    life_respawn_t respawn;
    life_stats_t last_stats;

    /* --- per voice --- */
    clock_divider_t voice_div[LIFE_NUM_VOICES];
    traversal_state_t trav[LIFE_NUM_VOICES];
    selection_state_t sel[LIFE_NUM_VOICES];
    voice_notes_t notes[LIFE_NUM_VOICES];
    voice_allocator_t allocator;

    uint32_t last_edge_us[LIFE_NUM_VOICES];
    uint32_t step_us[LIFE_NUM_VOICES];
    uint16_t last_played_mask[LIFE_NUM_VOICES];   /* for the UI flash */
    uint8_t voice_dev[LIFE_NUM_VOICES];           /* per-voice randomness CC */

    clock_divider_t gen_div;

    /* --- durable panel state (on_serialise) --- */
    uint16_t world_rows[LIFE_H];                  /* packed world, for saves */
    uint8_t v_enabled[LIFE_NUM_VOICES];
    uint8_t v_muted[LIFE_NUM_VOICES];
    uint8_t v_rate[LIFE_NUM_VOICES];
    uint8_t v_order[LIFE_NUM_VOICES];
    uint8_t v_rule[LIFE_NUM_VOICES];
    int8_t v_pitch[LIFE_NUM_VOICES];
    uint8_t v_length[LIFE_NUM_VOICES];

    uint8_t gen_rate;
    uint8_t respawn_floor;
    uint8_t respawn_amount;
    uint8_t respawn_stable;
    uint8_t freeze_life;

    /* --- durable preferences (on_serialise_settings) --- */
    uint8_t pref_root;        /* 0..11 */
    uint8_t pref_scale;       /* index into life_scale_masks */
    uint8_t pref_octave;      /* base octave, 1..7 */
    uint8_t pref_sink;
    uint8_t pref_port;
    uint8_t pref_send_cc;

    /* --- transient UI state, never serialised --- */
    uint8_t edit_voice;       /* which voice the per-voice settings pages edit */
    bool modifier_held;
    uint8_t solo_mask;
    uint8_t last_cc[LIFE_NUM_CCS];
    bool cc_primed;
    bool step_once_request;

    /* ---------------------------------------------------------------- */

    void reset_everything(void) {
        life_clear(&world);
        life_clear(&scratch);
        life_respawn_init(&respawn, 0x5eed1234u);
        last_stats.alive = last_stats.births = last_stats.deaths = 0;
        last_stats.unchanged = LIFE_CELLS;

        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            traversal_reset(&trav[v], TRAV_FORWARD, LIFE_W, 0x1000u + v * 977u);
            selection_reset(&sel[v], 0x2000u + v * 613u);
            voice_notes_init(&notes[v]);
            last_edge_us[v] = 0;
            step_us[v] = LIFE_DEFAULT_STEP_US;
            last_played_mask[v] = 0;
            voice_dev[v] = 0;
        }

        solo_mask = 0;
        edit_voice = 0;
        modifier_held = false;
        cc_primed = false;
        step_once_request = false;
        for (int i = 0; i < LIFE_NUM_CCS; ++i) last_cc[i] = 255;
    }

    void setup_default_panel_state() override {
        panel_t::setup_default_panel_state();

        /* Durable panel state defaults. SYSTEM_NOTES.md section 6b: this hook
           does NOT run on a staged load, which is how the IDE loads a panel, so
           anything that must exist at runtime is rebuilt in on_load_finished()
           rather than only here. */
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            v_enabled[v] = 1;
            v_muted[v] = 0;
            v_rate[v] = (uint8_t)(4 + v);          /* 8th, 4T, 1/4, 1/2 - four different rates */
            v_order[v] = TRAV_FORWARD;
            v_rule[v] = (uint8_t)(v == 0 ? SEL_FIRST : v == 1 ? SEL_WALK
                                        : v == 2   ? SEL_RANDOM
                                                   : SEL_LAST);
            v_pitch[v] = (int8_t)(v * -3);
            v_length[v] = 60;
        }
        gen_rate = 8;              /* one generation per bar */
        respawn_floor = 12;
        respawn_amount = 10;
        respawn_stable = 4;
        freeze_life = 0;

        pref_root = 0;
        pref_scale = 9;            /* minor pentatonic - forgiving by default */
        pref_octave = 3;
        pref_sink = LIFE_SINK_BOTH;
        pref_port = 3;             /* MIDI_PORT_1 */
        pref_send_cc = 1;

        reset_everything();
        rebuild_runtime();

        /* Seed a world so a fresh panel is immediately playable rather than
           silent - an empty Game of Life stays empty forever. */
        life_respawn_apply(&world, &respawn, 60);

        apply_scale_to_system();
    }

    void on_load_finished(void) override {
        panel_t::on_load_finished();
        clamp_settings();
        unpack_world();
        rebuild_runtime();
        apply_scale_to_system();
    }

    /* Everything that is derived rather than saved. Safe to call at any time. */
    void rebuild_runtime(void) {
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            traversal_reset(&trav[v], (traversal_order_t)v_order[v], LIFE_W, 0x1000u + v * 977u);
            selection_reset(&sel[v], 0x2000u + v * 613u);
            voice_notes_init(&notes[v]);
            last_edge_us[v] = 0;
            step_us[v] = LIFE_DEFAULT_STEP_US;
            last_played_mask[v] = 0;
        }
        /* The arena is zeroed before construction, which would leave these
           dividers with denominator 0. update() latches the requested values,
           but seed them anyway so no code path can divide by zero first. */
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            voice_div[v].numerator = life_rates[v_rate[v]].num;
            voice_div[v].denominator = life_rates[v_rate[v]].den;
        }
        gen_div.numerator = life_rates[gen_rate].num;
        gen_div.denominator = life_rates[gen_rate].den;

        life_respawn_init(&respawn, 0x5eed1234u);
        cc_primed = false;
        for (int i = 0; i < LIFE_NUM_CCS; ++i) last_cc[i] = 255;
    }

    /* A save can carry a value from an older build, or a field the save never
       wrote at all. SYSTEM_NOTES.md section 6b: absent fields keep whatever was
       already in the object, i.e. the PREVIOUS scene's value. Clamping on load
       is what stops that becoming an out-of-range index. */
    void clamp_settings(void) {
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            if (v_rate[v] >= LIFE_NUM_RATES) v_rate[v] = 4;
            if (v_order[v] >= TRAV_COUNT) v_order[v] = TRAV_FORWARD;
            if (v_rule[v] >= SEL_COUNT) v_rule[v] = SEL_FIRST;
            if (v_length[v] < 10) v_length[v] = 10;
            if (v_length[v] > 100) v_length[v] = 100;
            if (v_pitch[v] < -30) v_pitch[v] = -30;
            if (v_pitch[v] > 30) v_pitch[v] = 30;
            v_enabled[v] = v_enabled[v] ? 1 : 0;
            v_muted[v] = v_muted[v] ? 1 : 0;
        }
        if (gen_rate >= LIFE_NUM_RATES) gen_rate = 8;
        if (respawn_floor > 200) respawn_floor = 12;
        if (respawn_amount < 1) respawn_amount = 1;
        if (respawn_amount > 64) respawn_amount = 64;
        if (respawn_stable > 32) respawn_stable = 4;
        if (pref_root > 11) pref_root = 0;
        if (pref_scale >= LIFE_NUM_SCALES) pref_scale = 9;
        if (pref_octave < 1) pref_octave = 1;
        if (pref_octave > 7) pref_octave = 7;
        if (pref_sink > LIFE_SINK_BOTH) pref_sink = LIFE_SINK_BOTH;
        if (pref_port > 4) pref_port = 3;
        if (edit_voice >= LIFE_NUM_VOICES) edit_voice = 0;
    }

    /* current_key / current_scale are system globals shared across panels, so
       choosing a scale here drives the whole instrument rather than keeping a
       private harmonic state. */
    void apply_scale_to_system(void) {
        set_current_key_and_scale((uint8_t)(pref_root & 11), life_scale_masks[pref_scale]);
    }

    uint16_t scale_mask(void) const { return life_scale_masks[pref_scale]; }
    int root_note(void) const { return (int)pref_octave * 12 + (int)pref_root; }
    uint8_t midi_ports(void) const { return life_port_values[pref_port]; }

    /* --- world packing ---------------------------------------------------

       The world goes into the save as 16 row bitmasks rather than 256 JSON
       integers. */
    void pack_world(void) {
        for (int y = 0; y < LIFE_H; ++y) {
            uint16_t m = 0;
            for (int x = 0; x < LIFE_W; ++x)
                if (world.cell[y * LIFE_W + x]) m |= (uint16_t)(1u << x);
            world_rows[y] = m;
        }
    }

    void unpack_world(void) {
        for (int y = 0; y < LIFE_H; ++y)
            for (int x = 0; x < LIFE_W; ++x)
                world.cell[y * LIFE_W + x] = (world_rows[y] & (1u << x)) ? 1 : 0;
    }

    /* ================================================================== */
    /* Note output                                                        */
    /* ================================================================== */

    uint32_t source_id_for(int v, int note) const {
        return 0x11FE0000u | ((uint32_t)v << 8) | (uint32_t)(note & 127);
    }

    int midi_channel_for(int v) const {
        return (int)get_midi_channel_for_preset_idx(v, true);
    }

    void note_on(int v, int note, int velocity) {
        if (pref_sink == LIFE_SINK_SYNTH || pref_sink == LIFE_SINK_BOTH) {
            uint32_t sid = source_id_for(v, note);
            int old_voice = allocator.find_voice(sid);
            int new_voice = allocator.voice_allocate(sid, (uint8_t)(1 + v));
            if (new_voice >= 0) {
                if (new_voice != old_voice && old_voice >= 0) synth_note_up(old_voice);
                play_synth(new_voice, v, velocity, note << 8, true);
            }
        }
        if (pref_sink == LIFE_SINK_MIDI || pref_sink == LIFE_SINK_BOTH) {
            uint8_t ports = midi_ports();
            if (ports) midi_write(ports, MAKE_NOTEONMSG(midi_channel_for(v), note, velocity));
        }
    }

    void note_off(int v, int note) {
        if (pref_sink == LIFE_SINK_SYNTH || pref_sink == LIFE_SINK_BOTH) {
            uint32_t sid = source_id_for(v, note);
            int voice = allocator.find_voice(sid);
            if (voice >= 0) {
                synth_note_up(voice);
                allocator.voice_deallocate(sid);
            }
        }
        if (pref_sink == LIFE_SINK_MIDI || pref_sink == LIFE_SINK_BOTH) {
            uint8_t ports = midi_ports();
            if (ports) midi_write(ports, MAKE_NOTEOFFMSG(midi_channel_for(v), note, 0));
        }
    }

    /* The single exit path for a voice. Mute, rate change, transport stop,
       solo change and panel unload all come through here - stuck MIDI notes are
       the classic failure mode for a sequencer with an external sink, and one
       release function is what makes them impossible. */
    void release_voice(int v) {
        uint8_t released[LIFE_MAX_HELD];
        int n = voice_release_all(&notes[v], released);
        for (int i = 0; i < n; ++i) note_off(v, released[i]);
        last_played_mask[v] = 0;
    }

    void release_all_voices(void) {
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) release_voice(v);
    }

    bool voice_is_audible(int v) const {
        if (!v_enabled[v] || v_muted[v]) return false;
        if (solo_mask && !(solo_mask & (1u << v))) return false;
        return true;
    }

    /* ================================================================== */
    /* Sequencing - core0, IRQ context. Keep it short and deterministic.  */
    /* ================================================================== */

    void step_generation(void) {
        life_stats_t st;
        life_step(&world, &scratch, &st);
        for (int i = 0; i < LIFE_CELLS; ++i) world.cell[i] = scratch.cell[i];
        last_stats = st;

        if (life_respawn_tick(&respawn, &st, (int)respawn_floor, (int)respawn_stable))
            life_respawn_apply(&world, &respawn, (int)respawn_amount);

        if (pref_send_cc) send_simulation_ccs();
    }

    void fire_voice(int v) {
        int col = traversal_position(&trav[v], LIFE_W);
        uint16_t col_mask = life_column_mask(&world, col);
        int prev = sel[v].prev_row;
        uint16_t chosen = selection_pick(&sel[v], col_mask, (selection_rule_t)v_rule[v]);

        last_played_mask[v] = chosen;
        if (!chosen) return;                       /* an empty column is a rest */

        voice_dev[v] = (uint8_t)selection_deviation(&sel[v], prev);

        int ticks = voice_length_ticks((int)step_us[v], (int)v_length[v]);

        for (int y = 0; y < LIFE_H; ++y) {
            if (!(chosen & (1u << y))) continue;
            int degree = (15 - y) + (int)v_pitch[v];
            int note = life_degree_to_note(degree, root_note(), scale_mask());

            /* The automaton drives dynamics: a cell in a crowded neighbourhood
               hits harder than a lone one. */
            int n = life_neighbours(&world, col, y);
            int velocity = 68 + n * 7;
            if (velocity > 127) velocity = 127;

            if (voice_arm(&notes[v], note, velocity, ticks) >= 0)
                note_on(v, note, velocity);
        }
    }

    void on_sequence(int delta_time_us) override {
        int64_t phase = get_clock_phase();
        bool playing = is_transport_playing();

        /* Expire held notes first, so a note that ends exactly as the next one
           begins does not leave the new note's slot stolen from under it. */
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            uint8_t released[LIFE_MAX_HELD];
            int n = voice_tick(&notes[v], delta_time_us, released);
            for (int i = 0; i < n; ++i) note_off(v, released[i]);
        }

        if (!playing) {
            /* Transport stopped: silence everything and hold position. The
               world only advances via the action layer's single-step pad. */
            for (int v = 0; v < LIFE_NUM_VOICES; ++v)
                if (voice_num_held(&notes[v])) release_voice(v);
            if (step_once_request) {
                step_once_request = false;
                step_generation();
            }
            return;
        }

        if (step_once_request) {
            step_once_request = false;
            step_generation();
        }

        const life_rate_t *gr = &life_rates[gen_rate];
        int gen_edges = gen_div.update(phase, gr->num, gr->den, UPDATE_DIV_ON_QUARTER_NOTE);
        if (!freeze_life && gen_edges > 0 && sequencer_should_advance_playhead()) {
            /* A long stall can report many crossed edges at once. Cap the catch
               up so a seek cannot burn hundreds of generations inside an IRQ. */
            if (gen_edges > 4) gen_edges = 4;
            for (int i = 0; i < gen_edges; ++i) step_generation();
        }

        uint32_t now = time_us();
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            const life_rate_t *r = &life_rates[v_rate[v]];
            int edges = voice_div[v].update(phase, r->num, r->den, UPDATE_DIV_ON_QUARTER_NOTE);
            if (edges <= 0) continue;

            if (!voice_is_audible(v)) {
                if (voice_num_held(&notes[v])) release_voice(v);
                continue;
            }

            if (last_edge_us[v]) {
                uint32_t dt = now - last_edge_us[v];
                if (dt > 1000 && dt < 30000000u) step_us[v] = dt;
            }
            last_edge_us[v] = now;

            if (sequencer_should_advance_playhead())
                traversal_advance(&trav[v], (traversal_order_t)v_order[v], LIFE_W);
            fire_voice(v);
        }
    }

    /* --- simulation CCs --------------------------------------------------

       Sent on generation edges only, never per sequence tick - that IS the
       throttle - and only when a value actually changed, so a settled world
       stops talking instead of flooding the bus. */
    void send_cc_if_changed(int idx, int cc, int value) {
        if (value < 0) value = 0;
        if (value > 127) value = 127;
        if (cc_primed && last_cc[idx] == (uint8_t)value) return;
        last_cc[idx] = (uint8_t)value;
        uint8_t ports = midi_ports();
        if (ports) midi_write_cc(ports, get_system_midi_channel() - 1, cc, value);
    }

    void send_simulation_ccs(void) {
        send_cc_if_changed(0, LIFE_CC_DENSITY, last_stats.alive * 127 / LIFE_CELLS);
        send_cc_if_changed(1, LIFE_CC_BIRTHS, last_stats.births * 127 / 64);
        send_cc_if_changed(2, LIFE_CC_DEATHS, last_stats.deaths * 127 / 64);
        send_cc_if_changed(3, LIFE_CC_STABILITY, last_stats.unchanged * 127 / LIFE_CELLS);
        for (int v = 0; v < LIFE_NUM_VOICES; ++v)
            send_cc_if_changed(4 + v, LIFE_CC_VOICE_RND + v, voice_dev[v]);
        cc_primed = true;
    }

    /* ================================================================== */
    /* Drawing and touch - core0 foreground                               */
    /* ================================================================== */

    /* Which voices are sitting on this column, as a bitmask. */
    uint8_t voices_on_column(int x) const {
        uint8_t m = 0;
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            if (!voice_is_audible(v)) continue;
            if (traversal_position(&trav[v], LIFE_W) == x) m |= (uint8_t)(1u << v);
        }
        return m;
    }

    uint32_t cell_colour(int x, int y, bool dim) const {
        bool alive = world.cell[y * LIFE_W + x] != 0;
        uint8_t on_col = voices_on_column(x);

        if (on_col) {
            for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
                if (!(on_col & (1u << v))) continue;
                /* the cell this voice actually chose flashes at full brightness */
                if (last_played_mask[v] & (1u << y)) return life_voice_bright[v];
            }
            if (alive) return dim ? LIFE_COL_ALIVE_DIM : LIFE_COL_ALIVE;
            /* the playhead column itself, tinted by its lowest-numbered voice */
            for (int v = 0; v < LIFE_NUM_VOICES; ++v)
                if (on_col & (1u << v)) return life_voice_dim[v];
        }

        if (alive) return dim ? LIFE_COL_ALIVE_DIM : LIFE_COL_ALIVE;
        return 0;
    }

    void draw_world(bool dim) {
        for (int y = 0; y < LIFE_H; ++y)
            for (int x = 0; x < LIFE_W; ++x) {
                if (x == LIFE_MODIFIER_X && y == LIFE_MODIFIER_Y) continue;
                set_led(x, y, cell_colour(x, y, dim));
            }
    }

    /* The world is painted by tapping. Widgets, not raw touch: SYSTEM_NOTES.md
       section 4 is emphatic that a raw pressure dip reads as a release and
       pressure sliding in from a neighbour reads as a press. */
    void handle_world_touch(void) {
        for (int y = 0; y < LIFE_H; ++y) {
            for (int x = 0; x < LIFE_W; ++x) {
                if (x == LIFE_MODIFIER_X && y == LIFE_MODIFIER_Y) continue;
                if (invisible_button(x, y, NOT_ISOLATED) && is_last_widget_pressed()) {
                    /* on_ui and on_sequence share the world, and on_sequence can
                       interrupt this at any instruction. */
                    on_sequence_lock_guard_t guard;
                    life_toggle(&world, x, y);
                }
            }
        }
    }

    /* --- the held-modifier action layer ---------------------------------- */

    void draw_action_layer(void) {
        draw_world(true);

        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            bool audible = voice_is_audible(v);
            if (button(v, 14, audible ? life_voice_bright[v] : LIFE_COL_OFF, NOT_ISOLATED,
                       "mute voice")) {
                v_muted[v] = v_muted[v] ? 0 : 1;
                if (!voice_is_audible(v)) release_voice(v);
            }
            bool soloed = (solo_mask & (1u << v)) != 0;
            if (button(v + 4, 14, soloed ? life_voice_bright[v] : life_voice_dim[v],
                       NOT_ISOLATED, "solo voice")) {
                solo_mask ^= (uint8_t)(1u << v);
                for (int i = 0; i < LIFE_NUM_VOICES; ++i)
                    if (!voice_is_audible(i)) release_voice(i);
            }
        }

        if (button(0, 15, LIFE_COL_DANGER, NOT_ISOLATED, "clear the world")) {
            on_sequence_lock_guard_t guard;
            life_clear(&world);
        }
        if (button(1, 15, LIFE_COL_ACTION, NOT_ISOLATED, "respawn cells now")) {
            on_sequence_lock_guard_t guard;
            life_respawn_apply(&world, &respawn, (int)respawn_amount);
        }
        if (button(2, 15, freeze_life ? LIFE_COL_DANGER : LIFE_COL_ACTION, NOT_ISOLATED,
                   "freeze evolution"))
            freeze_life = freeze_life ? 0 : 1;
        if (button(3, 15, LIFE_COL_ACTION, NOT_ISOLATED, "step one generation"))
            step_once_request = true;
        if (button(4, 15, is_transport_playing() ? LIFE_COL_ACTION : LIFE_COL_OFF, NOT_ISOLATED,
                   "start or stop")) {
            if (is_transport_playing()) {
                stop_transport();
                release_all_voices();
            } else {
                start_transport();
            }
        }
    }

    /* --- settings pages -------------------------------------------------

       Rendered with the system helpers, which return the left-button edit
       delta. The right pair page; the left pair adjust. Both are system
       territory on every faceplate, so the panel never touches them. */

    int settings_page_count(void) { return 15; }
    int get_num_panel_settings_pages(void) override { return settings_page_count(); }

    static int clamp_int(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }

    void draw_settings(int page) {
        int idx = -1 - page;                       /* page -1 is our page 0 */
        char buf[8];
        int v = edit_voice;

        switch (idx) {
        case 0: {
            int d = draw_system_style_enum_settings_page("KEY ", pref_root, life_note_names, 12);
            if (d) { pref_root = (uint8_t)((pref_root + d + 120) % 12); apply_scale_to_system(); }
            break;
        }
        case 1: {
            int d = draw_system_style_enum_settings_page("SCAL", pref_scale, life_scale_names,
                                                        LIFE_NUM_SCALES);
            if (d) {
                pref_scale = (uint8_t)clamp_int(pref_scale + d, 0, LIFE_NUM_SCALES - 1);
                apply_scale_to_system();
            }
            break;
        }
        case 2: {
            snprintf(buf, sizeof(buf), "%d", pref_octave);
            int d = draw_system_style_settings_page("OCT ", buf, pref_octave * 100 / 7);
            if (d) pref_octave = (uint8_t)clamp_int(pref_octave + d, 1, 7);
            break;
        }
        case 3: {
            int d = draw_system_style_enum_settings_page("GEN ", gen_rate, life_rate_names,
                                                        LIFE_NUM_RATES);
            if (d) gen_rate = (uint8_t)clamp_int(gen_rate + d, 0, LIFE_NUM_RATES - 1);
            break;
        }
        case 4: {
            snprintf(buf, sizeof(buf), "%d", respawn_floor);
            int d = draw_system_style_settings_page("FLOR", buf, respawn_floor * 100 / 64);
            if (d) respawn_floor = (uint8_t)clamp_int(respawn_floor + d, 0, 64);
            break;
        }
        case 5: {
            snprintf(buf, sizeof(buf), "%d", respawn_amount);
            int d = draw_system_style_settings_page("SEED", buf, respawn_amount * 100 / 64);
            if (d) respawn_amount = (uint8_t)clamp_int(respawn_amount + d, 1, 64);
            break;
        }
        case 6: {
            snprintf(buf, sizeof(buf), "%d", respawn_stable);
            int d = draw_system_style_settings_page("STAB", buf, respawn_stable * 100 / 32);
            if (d) respawn_stable = (uint8_t)clamp_int(respawn_stable + d, 0, 32);
            break;
        }
        case 7: {
            int d = draw_system_style_enum_settings_page("OUT ", pref_sink, life_sink_names, 3);
            if (d) {
                release_all_voices();              /* never strand a note on the old sink */
                pref_sink = (uint8_t)clamp_int(pref_sink + d, 0, 2);
            }
            break;
        }
        case 8: {
            int d = draw_system_style_enum_settings_page("PORT", pref_port, life_port_names, 5);
            if (d) {
                release_all_voices();
                pref_port = (uint8_t)clamp_int(pref_port + d, 0, 4);
            }
            break;
        }
        case 9: {
            bool on = pref_send_cc != 0;
            int d = draw_system_style_bool_settings_page("SIM ", on);
            if (d) pref_send_cc = on ? 0 : 1;
            break;
        }
        case 10: {
            snprintf(buf, sizeof(buf), "V%d", v + 1);
            int d = draw_system_style_settings_page("EDIT", buf, (v + 1) * 25,
                                                   0, 0, life_voice_bright[v]);
            if (d) edit_voice = (uint8_t)clamp_int(v + d, 0, LIFE_NUM_VOICES - 1);
            break;
        }
        case 11: {
            int d = draw_system_style_enum_settings_page("RATE", v_rate[v], life_rate_names,
                                                        LIFE_NUM_RATES, life_voice_bright[v]);
            if (d) {
                release_voice(v);                  /* the step length just changed */
                v_rate[v] = (uint8_t)clamp_int(v_rate[v] + d, 0, LIFE_NUM_RATES - 1);
                last_edge_us[v] = 0;
                step_us[v] = LIFE_DEFAULT_STEP_US;
            }
            break;
        }
        case 12: {
            int d = draw_system_style_enum_settings_page("ORDR", v_order[v], life_trav_names,
                                                        TRAV_COUNT, life_voice_bright[v]);
            if (d) v_order[v] = (uint8_t)clamp_int(v_order[v] + d, 0, TRAV_COUNT - 1);
            break;
        }
        case 13: {
            int d = draw_system_style_enum_settings_page("RULE", v_rule[v], life_sel_names,
                                                        SEL_COUNT, life_voice_bright[v]);
            if (d) v_rule[v] = (uint8_t)clamp_int(v_rule[v] + d, 0, SEL_COUNT - 1);
            break;
        }
        case 14: {
            /* Pitch offset and note length share a page to keep the page count
               walkable with two buttons: length is the bar, pitch the number. */
            snprintf(buf, sizeof(buf), "%+d", v_pitch[v]);
            int d = draw_system_style_settings_page("PTCH", buf, v_length[v],
                                                   0, 0, life_voice_bright[v]);
            if (d) v_pitch[v] = (int8_t)clamp_int(v_pitch[v] + d, -30, 30);
            break;
        }
        default:
            break;
        }
    }

    void on_ui(int delta_time_us) override {
        (void)delta_time_us;

        int page = get_scroll_page();
        if (page < 0) {
            draw_settings(page);
            return;
        }

        leds_clear();

        /* SYSTEM_NOTES.md section 4: emit the modifier ONCE, before anything
           that tests it, and NOT_ISOLATED because being held while another pad
           is tapped IS the gesture. Everything else reads the member. */
        modifier_held = shift_button(LIFE_MODIFIER_X, LIFE_MODIFIER_Y, LIFE_COL_MODIFIER,
                                     NOT_ISOLATED, "hold for mutes, clear, transport");

        if (modifier_held) {
            draw_action_layer();
            set_help_text("Life #fc2#*actions#. - mute, solo, clear, seed, freeze, step, play");
        } else {
            draw_world(false);
            handle_world_touch();
            set_help_text("Life - #fc2#*%d#. alive, %s %s", last_stats.alive,
                          life_note_names[pref_root], life_scale_long_names[pref_scale]);
        }
    }

    /* ================================================================== */
    /* Persistence                                                        */
    /* ================================================================== */

    int get_version(void) override { return 1; }

    bool on_serialise(serialiser_t &s, int version) override {
        (void)version;
        pack_world();

        /* SYSTEM_NOTES.md section 6b: named fields are only written back when
           PRESENT, so a field a save omits silently keeps the PREVIOUS scene's
           value. Reset to a known default before OBJECT_BEGIN so an absent
           field loads as a default rather than as whatever was last on screen.

           ONLY when loading. The same serialise function runs for both
           directions, and resetting on the way out would write defaults to disk
           and throw away the state the user asked to save. */
        if (is_serialise_in_progress == 1) setup_default_panel_state_fields_only();

        OBJECT_BEGIN(s);
        FIELD("world", world_rows);
        FIELD("ven", v_enabled);
        FIELD("vmute", v_muted);
        FIELD("vrate", v_rate);
        FIELD("vordr", v_order);
        FIELD("vrule", v_rule);
        FIELD("vptch", v_pitch);
        FIELD("vlen", v_length);
        FIELD("gen", gen_rate);
        FIELD("floor", respawn_floor);
        FIELD("seed", respawn_amount);
        FIELD("stab", respawn_stable);
        FIELD("freeze", freeze_life);
        OBJECT_END(s);

        clamp_settings();
        unpack_world();
        return true;
    }

    /* The reset half of setup_default_panel_state(), without the world seeding
       or the runtime rebuild, so on_serialise can use it as a known baseline. */
    void setup_default_panel_state_fields_only(void) {
        for (int v = 0; v < LIFE_NUM_VOICES; ++v) {
            v_enabled[v] = 1;
            v_muted[v] = 0;
            v_rate[v] = (uint8_t)(4 + v);
            v_order[v] = TRAV_FORWARD;
            v_rule[v] = (uint8_t)(v == 0 ? SEL_FIRST : v == 1 ? SEL_WALK
                                        : v == 2   ? SEL_RANDOM
                                                   : SEL_LAST);
            v_pitch[v] = (int8_t)(v * -3);
            v_length[v] = 60;
        }
        gen_rate = 8;
        respawn_floor = 12;
        respawn_amount = 10;
        respawn_stable = 4;
        freeze_life = 0;
    }

    bool on_serialise_settings(serialiser_t &s, int version) override {
        (void)version;
        if (is_serialise_in_progress == 1) {   /* load only - see on_serialise */
            pref_root = 0;
            pref_scale = 9;
            pref_octave = 3;
            pref_sink = LIFE_SINK_BOTH;
            pref_port = 3;
            pref_send_cc = 1;
        }

        OBJECT_BEGIN(s);
        FIELD("root", pref_root);
        FIELD("scale", pref_scale);
        FIELD("oct", pref_octave);
        FIELD("sink", pref_sink);
        FIELD("port", pref_port);
        FIELD("cc", pref_send_cc);
        OBJECT_END(s);

        clamp_settings();
        return true;
    }
};
